name: Request new prefix
description: Add metadata about a database, ontology, or other authority that issues stable
  identifiers.
title: Add prefix [X]
labels: [ New, Prefix ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new prefix request form!

        The Bioregistry mints prefixes that correspond to different nomenclature authorities. This could be appropriate for an ontology, database, or other terminology.
  - type: input
    id: prefix
    attributes:
      label: Prefix
      description: What is the desired prefix? Don't include any strange punctuation or spaces. Keep it lowercase.
      placeholder: ex. chebi
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Name
      description: What is the name of the nomenclature authority associated with this prefix? Please write out acronyms in full.
      placeholder: ex. Chemical Entities of Biological Interest
    validations:
      required: true
  - type: input
    id: homepage
    attributes:
      label: Homepage
      description: |
        What is the website of the nomenclature authority associated with this prefix?

        If your resource is part of a website that issues several resources, try picking a page that's as specific as possible.
      placeholder: ex. https://www.ebi.ac.uk/chebi/
    validations:
      required: true
  - type: input
    id: repository
    attributes:
      label: Source Code Repository
      description: |
        What is the version control repository associated with this prefix?

        Typically, this is a URL to a repository on GitHub, GitLab, BitBucket, etc. for resources like ontologies. This is useful in two ways: first, it allows to quickly find the related issue tracker. Second, it enables external contributions.
      placeholder: ex. https://github.com/ebi-chebi/ChEBI
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe this resource in a sentence or two of english prose. A good description says what kind of entities the resource makes identifiers for, why the resource exists, and who might want to use it.
      placeholder: Tell us about this nomenclature authority!
      # value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: license
    attributes:
      label: License
      description: |
        What is the repository's license? Write with a SPDX identifier, if possible.
      placeholder: ex. CC0
  - type: input
    id: publications
    attributes:
      label: Publications
      description: |
        If you have a PubMed identifier, PMC identifier, or DOI with an article associated with this resource, please put it here. Please write publications using CURIE syntax. Please delimit multiple unique publications with a pipe "|" character. You only need one CURIE for each publication.
      placeholder: ex. doi:10.1101/2022.07.08.499378 | pubmed:33290552 | pmc:PMC4383985

  - type: input
    id: example
    attributes:
      label: Example Local Unique Identifier
      description: Please provide an example local unique identifier from the nomenclature authority. This should NOT be written as a CURIE nor include the prefix.
      placeholder: ex. 1234
    validations:
      required: true
  - type: input
    id: pattern
    attributes:
      label: Regular Expression Pattern for Local Unique Identifier
      description: |
        The regular expression (regex) that matches all of the identifiers in the nomenclature authority. If you're not sure how to write a regex, please make sure you've included an example identifier and we'll be happy to help you out!

        Do include a carat `^` at the beginning and a dollar sign `$` at the end to signify that your pattern only matches the identifier, and not potentially any other parts of the string.

        Do not include a redundant prefix within the pattern (e.g., do not write `^CHEBI:\d+$`).
      placeholder: ex. ^\d+$
    validations:
      required: false
  - type: input
    id: url
    attributes:
      label: URI Format String
      description: |
        A URI format string is a URI with a placeholder (`$1`) for the local unique identifier that can be used in combination with a given local unique identifier to make a URI for the local unique identifier.

        While it is encouraged that these URIs can resolved to a webpage, it is not strictly necessary, e.g in the case of many ontologies, URIs are auto-generated.
      placeholder: ex. `https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:$1`
    validations:
      required: false
  - type: input
    id: wikidata_property
    attributes:
      label: Wikidata Property
      description: A Wikidata property for connecting to local unique identifiers in this resource, e.g., [P683](https://www.wikidata.org/wiki/Property:P683) for ChEBI
      placeholder: ex. P683
    validations:
      required: false

  - type: input
    id: contributor_name
    attributes:
      label: Contributor Name
      description: Please provide your name so we can attribute this contribution to you.
      placeholder: ex. Charles Tapley Hoyt
    validations:
      required: true
  - type: input
    id: contributor_github
    attributes:
      label: Contributor GitHub
      description: Please provide your GitHub username (no @ symbol) so we can attribute this contribution to you.
      placeholder: ex. cthoyt
    validations:
      required: true
  - type: input
    id: contributor_orcid
    attributes:
      label: Contributor ORCiD
      description: |
        Please provide your ORCiD identifier so we can attribute this contribution to you.

        For proper attribution of your contribution, please provide a valid ORCiD. If you don't have an ORCiD, please visit [ORCiD's registration page](https://orcid.org/register) to create one for free.
      placeholder: ex. 0000-0003-4423-4370
    validations:
      required: true
  - type: input
    id: contributor_email
    attributes:
      label: Contributor Email
      description: Please provide your email address (optional) so others can contact you regarding your contribution
      placeholder: ex. cthoyt@gmail.com

  - type: input
    id: contact_name
    attributes:
      label: Contact Name
      description: Please provide the name of the primary contact for this resource, if known. If you are contributing your own resource, please fill out this field even though it is redundant of the contributor field.
      placeholder: ex. Charles Tapley Hoyt
  - type: input
    id: contact_orcid
    attributes:
      label: Contact ORCiD
      description: Please provide the ORCiD identifier of the primary contact for this resource, if known. If you are contributing your own resource, please fill out this field even though it is redundant of the contributor field.
      placeholder: ex. 0000-0003-4423-4370
  - type: input
    id: contact_github
    attributes:
      label: Contact GitHub
      description: Please provide the GitHub handle of the primary contact for this resource, if known. If you are contributing your own resource, please fill out this field even though it is redundant of the contributor field.
      placeholder: ex. cthoyt
  - type: input
    id: contact_email
    attributes:
      label: Contact Email
      description: Please provide the email address of the primary contact for this resource, if known.
      placeholder: ex. cthoyt@gmail.com

  - type: textarea
    id: comments
    attributes:
      label: Additional Comments
      description: If you have any additional comments about this nomenclature authority to include in the Bioregistry that don't exactly belong in the description, please leave them here.
    validations:
      required: false
