name: Request new prefix
description: Add metadata about a database, ontology, or other authority that issues stable
  identifiers.
title: "[Resource]:"
labels: [ New, Prefix ]
assignees:
  - cthoyt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new prefix request form!

        The Bioregistry mints prefixes that correspond to different nomenclature authorities. This could be appropriate for an ontology, database, or other terminology.
  - type: input
    id: prefix
    attributes:
      label: Prefix
      description: What is the desired prefix? Don't include any strange punctuation or spaces. Keep it lowercase.
      placeholder: ex. chebi
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Name
      description: What is the name of the nomenclature authority associated with this prefix? Please write out acronyms in full.
      placeholder: ex. Chemical Entities of Biological Interest
    validations:
      required: true
  - type: input
    id: homepage
    attributes:
      label: Homepage
      description: |
        What is the website of the nomenclature authority associated with this prefix?

        If your resource is part of a website that issues several resources, try picking a page that's as specific as possible.
      placeholder: ex. https://www.ebi.ac.uk/chebi/
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe this resource in a sentence or two of english prose. A good description says what kind of entities the resource makes identifiers for, why the resource exists, and who might want to use it.
      placeholder: Tell us about this nomenclature authority!
      # value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: example
    attributes:
      label: Example Identifier
      description: Please provide an example identifier from the nomenclature authority. While this field isn't required, it's HIGHLY suggested.
      placeholder: ex. 1234
    validations:
      required: false
  - type: input
    id: pattern
    attributes:
      label: Regular Expression Pattern
      description: |
        The regular expression (regex) that matches all of the identifiers in the nomenclature authority. If you're not sure how to write a regex, please make sure you've included an example identifier and we'll be happy to help you out!

        Do include a carat `^` at the beginning and a dollar sign `$` at the end to signify that your pattern only matches the identifier, and not potentially any other parts of the string.

        Do not include a redundant prefix within the pattern (e.g., do not write `^CHEBI:\d+$`).
        If your identifiers contain a redundant prefix, simply write it as write it simply as `^\d+$` and follow the instructions below in the  "Redundant Prefix" section to capture the redundant `CHEBI:`. This is important for some communities using the Bioregistry.
      placeholder: ex. ^\d+$
    validations:
      required: false
  - type: input
    id: banana
    attributes:
      label: Redundant Prefix in Regular Expression Pattern
      description: If your nomenclature authority's regex pattern includes a redundant prefix, then you can write it out exactly as it appears in the identifier here. For example, ChEBI's redundant prefix should be written as `CHEBI:`.
      placeholder: "ex. CHEBI:"
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Additional Comments
      description: If you have any additional comments about this nomenclature authority to include in the Bioregistry that don't exactly belong in the description, please leave them here.
    validations:
      required: false
