name: Add provider for resource
description: Add a URL for resolving identifiers in a given resource
title: Add provider for [X]
labels: [ Provider, New ]
assignees:
  - cthoyt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out the new provider form!
  - type: input
    id: prefix
    attributes:
      label: Prefix
      description: What is the Bioregistry prefix of the resource?
      placeholder: ex. chebi
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Provider Format URL
      description: A URL where any occurrence of `$1` gets replaced with the identifier
      placeholder: ex. `https://www.ebi.ac.uk/chebi/searchId.do?chebiId=$1`
    validations:
      required: true
