title: Bioregistry
author: Charles Tapley Hoyt
email: cthoyt@gmail.com
description: >
  An integrative meta-registry of biological databases, ontologies, and nomenclatures.

twitter_username: bioregistry
github_username:  bioregistry

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
