# This file configures the continuous integration (CI) system on GitHub.
# Introductory materials can be found here: https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions.
# Documentation for editing this file can be found here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14", "3.10"]
        tox-command: ["lint", "pyroma", "mypy"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Install uv"
        uses: "astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78" # v7.6.0
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: "Run command"
        run: |
          uvx -p ${{ matrix.python-version }} --with tox-uv tox -e ${{ matrix.tox-command }}

      # Inspired by https://github.com/astral-sh/uv/blob/98523e2014e9a5c69706623344026d76296e178f/.github/workflows/ci.yml#L67C1-L70C61
      - name: "Prettier"
        run: |
          npx prettier --prose-wrap always --check "**/*.md"

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # We only test documentation on the latest version
        # sphinx 8.0 / sphinx-rtd-theme 3.0 discontinued Python 3.9 support
        # a year early, which prompted re-thinking about this.
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Install uv"
        uses: "astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78" # v7.6.0
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Install dependencies
        run: |
          sudo apt-get install graphviz
      - name: Check RST conformity with doc8
        run: uvx -p ${{ matrix.python-version }} --with tox-uv tox -e doc8
      - name: Check docstring coverage
        run: uvx -p ${{ matrix.python-version }} --with tox-uv tox -e docstr-coverage
      - name: Check documentation build with Sphinx
        run: uvx -p ${{ matrix.python-version }} --with tox-uv tox -e docs-test
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.14", "3.10"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Install uv"
        uses: "astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78" # v7.6.0
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        if: matrix.os == 'ubuntu-latest'

      - name: Start blazegraph and virtuoso triplestores with docker
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker compose up -d
          sleep 20
          docker compose exec virtuoso isql -U dba -P dba exec='GRANT "SPARQL_SELECT_FED" TO "SPARQL";'

      - name: Test with pytest and generate coverage file
        run: uvx -p ${{ matrix.python-version }} --with tox-uv tox -e py

      - name: Run doctests
        run: uvx -p ${{ matrix.python-version }} --with tox-uv tox -e doctests

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        if: success()
        with:
          file: coverage.xml
