name: Test Update Data
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Create local changes
        id: update
        run: |
          pip install -e .[charts]
          bioregistry update
        env:
          BIOPORTAL_API_KEY: ${{ secrets.BIOPORTAL_API_KEY }}
      - name: Check environment
        run: echo ${{ steps.update.outputs.BR_UPDATED }}
      - name: Git status
        run: git status
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --all -m "📮 Automatically update"
      - name: Git status
        run: git status
